### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Suor** [Suor/django-pickling#3]

**Comment by km-pg** [comment]
One thing that needs to be fixed: Replace izip with just zip. In Python 3, zip returns an iterator, so they got rid of izip.
http://www.diveintopython3.net/porting-code-to-python-3-with-2to3.html#itertools

**Comment by Suor** [comment]
Using `izip()` is faster in Python 2. So it should use `izip()` in Python 2 and built-in `zip()` in Python 3.

**Comment by tspecht** [comment]
Any news on this?

**Comment by Suor** [comment]
Done by 33928db8b5ce3cda76100ee34a71097e57e31895.
