### ISSUE TITLE
Better to mark cache as global?

### ISSUE THREAD

**Issue by Proper-Job** [Suor/django-pickling#8]
Hi
Wouldn't it be better to mark [_cache](https://github.com/Suor/django-pickling/blob/master/django_pickling.py#L12) as a global var instead of relying on the default to be shared between function invocations?

**Comment by Suor** [comment]
Global vars access is much slower. This is common microoptimization.

**Comment by Proper-Job** [comment]
@Suor I did not know that.  Thank you for shedding light on that for me :)
